[package]
name = "test_pipes"
version = "0.1.0"
authors = ["Jesper Axelsson <jesperaxe@gmail.com>"]

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "ntdef", "namedpipeapi", "minwinbase", "minwindef", "winbase", "handleapi", "fileapi" ] }
