[package]
name = "serious_organizer_server"
version = "0.1.1"
authors = ["Jesper Axelsson <jesperaxe@gmail.com>"]

[dependencies]
serious_organizer_lib = { git = "https://github.com/JesperAxelsson/SeriousOrganizerLib" }
rmp-serde = "0.13.7"
serde = "1.0.53"
serde_derive = "1.0.53"
time = "0.1.40"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["winuser", "ntdef", "namedpipeapi", "minwinbase", "minwindef", "winbase", "handleapi", "fileapi" ] }
